// src/routes/about.svelte
<script>
	var socials = [
		{ url: "https://github.com/imvaskel", name: "GitHub"},
		{ url: "https://twitter.com/imvaskel", name:"Twitter"},
		{ url: "https://discord.com/users/447422100798570496", name: "Discord (Vaskel#0001)"},
		{ url: "mailto:contact@vaskel.gay", name: "Email"}
	]
</script>

<svelte:head>
	<title>About</title>
	<link rel="stylesheet" href="./style.css">
</svelte:head>

<div class="container">
	<h1>About Me</h1>

	<p>
		I'm not too sure what to put here but here we go. Bisexual programmer and gamer from the US. I wouldn't say I'm 
		the best at programming but I manage.
	</p>


	<h2>Social Media</h2>

	<ul>
		{ #each socials as social}
			<li>
				<a href="{social.url}">{social.name}</a>
			</li>
		{/each}
	</ul>

	<h2>Languages</h2>

	<ul>
		<li>Python. I know this language the most and like it the most.</li>
		<li>Kotlin. I know this a decent amount and also like it.</li>
		<li>Java/C#. I know enough of these 2 languages to manage, though they aren't my favorite.</li>
	</ul>
</div>

<style>
	.container {
		padding-left: 2%;
		padding-top: 2%;
		font-size: large;
		display: flex;
		flex-direction: column;
		color: #E91E63;
	}

	p, li {
		color: white;
	}

	h1, h2, p,li {
		padding-bottom: 2%;
	}

	li::before {
		color: #b0003a
	}
</style>

// pages/about.tsx
import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styled from "styled-components";
import Layout from "../components/layout";
import styles from "../styles/globals.module.css";

const Header = styled.h1`
  font-size: 2em;
  padding-bottom: 2%;
`;

const Paragraph = styled.p`
  font-weight: 400;
  padding-bottom: 2%;
  padding-left: 0.5%;
`;

const LI = styled.li`
  padding-bottom: 2%;
  font-weight: 400;
`;

const About: NextPage = () => {
  return (
    <Layout>
      <div className={styles.content} style={{ fontSize: "large" }}>
        <Head>
          <title>About</title>
        </Head>
        <Header>About Me</Header>
        <Paragraph>
          I'm not too sure what to put here, but here we go. Hi, I'm Vaskel. I'm a
          gay high schooler from the US, I play video games and program. I
          know, so interesting. The best place to contact me is on discord. You can find my prounouns page {" "}
          <a
            style={{
              color: "#E91E63",
            }}
            href="https://en.pronouns.page/@vaskel"
          >
            here
          </a>.
          <br />
        </Paragraph>
        <Header>Social Media</Header>
        <Paragraph>You can find my social media in the footer.</Paragraph>
        <Header>Languages</Header>
        <Paragraph>
          These are my most proficient languages ranked from highest to lowest.
        </Paragraph>
        <Paragraph>
          Python: This is my first language and my most liked one.
        </Paragraph>
        <Paragraph>
          Kotlin: This is a language that I know decently well and like to program
          in if it isn't python.
        </Paragraph>
        <Paragraph>
          Rust: I'm learning this one and enjoy it, though I wouldn't say I know
          it well.
        </Paragraph>
        <Paragraph>
          C#/Java: I know both of these enough to manage, though I do not like
          them that much.{" "}
        </Paragraph>
      </div>
    </Layout>
  );
};

export default About;
